"""User Memory Service - stores user profile information in markdown files.

Each user has a user.md file containing:
- User ID (for linking with sessions)
- Display name
- About/description
- Registration date
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Optional


class UserMemoryService:
    """Service for persisting user profile to markdown file."""

    def __init__(self, base_dir: str = "memory_dir/users"):
        """Initialize the user memory service.
        
        Args:
            base_dir: Base directory for storing user files.
        """
        self.base_dir = Path(base_dir)
        self.base_dir.mkdir(parents=True, exist_ok=True)

    def _get_user_file(self, user_id: str) -> Path:
        """Get file path for user profile."""
        return self.base_dir / f"{user_id}.md"

    def create_user_profile(
        self,
        user_id: str,
        login: str,
        display_name: str,
        about: Optional[str] = None,
    ) -> None:
        """Create user profile markdown file.
        
        Args:
            user_id: User UUID
            login: User login
            display_name: How to address the user
            about: Free-form user description
        """
        user_file = self._get_user_file(user_id)
        
        content = f"""# User Profile: {display_name}

## Identity

- **User ID:** `{user_id}`
- **Login:** `{login}`
- **Display Name:** {display_name}
- **Registered:** {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")}

## About

{about or "_No description provided._"}

---

## Notes

_This file is automatically generated and used by the chat memory agent to personalize conversations._
"""
        
        with open(user_file, "w", encoding="utf-8") as f:
            f.write(content)

    def update_user_profile(
        self,
        user_id: str,
        display_name: Optional[str] = None,
        about: Optional[str] = None,
    ) -> bool:
        """Update user profile.
        
        Args:
            user_id: User UUID
            display_name: New display name (optional)
            about: New about text (optional)
            
        Returns:
            True if updated, False if user not found.
        """
        user_file = self._get_user_file(user_id)
        
        if not user_file.exists():
            return False
        
        content = user_file.read_text(encoding="utf-8")
        
        if display_name:
            # Update display name in header
            lines = content.split("\n")
            for i, line in enumerate(lines):
                if line.startswith("# User Profile:"):
                    lines[i] = f"# User Profile: {display_name}"
                elif line.startswith("- **Display Name:**"):
                    lines[i] = f"- **Display Name:** {display_name}"
            content = "\n".join(lines)
        
        if about is not None:
            # Update about section
            lines = content.split("\n")
            in_about = False
            about_start = -1
            about_end = -1
            
            for i, line in enumerate(lines):
                if line.strip() == "## About":
                    in_about = True
                    about_start = i + 2  # Skip header and empty line
                elif in_about and line.startswith("---"):
                    about_end = i - 1  # Before the separator
                    break
            
            if about_start > 0 and about_end > 0:
                new_about = about or "_No description provided._"
                lines = lines[:about_start] + [new_about, ""] + lines[about_end + 1:]
                content = "\n".join(lines)
        
        # Add updated timestamp
        updated_line = f"- **Last Updated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}"
        if "**Last Updated:**" in content:
            lines = content.split("\n")
            for i, line in enumerate(lines):
                if "**Last Updated:**" in line:
                    lines[i] = updated_line
                    break
            content = "\n".join(lines)
        else:
            # Add after Registered line
            lines = content.split("\n")
            for i, line in enumerate(lines):
                if "**Registered:**" in line:
                    lines.insert(i + 1, updated_line)
                    break
            content = "\n".join(lines)
        
        with open(user_file, "w", encoding="utf-8") as f:
            f.write(content)
        
        return True

    def get_user_profile(self, user_id: str) -> str:
        """Read user profile.
        
        Returns:
            Markdown content of user profile, or empty string if not found.
        """
        user_file = self._get_user_file(user_id)
        if user_file.exists():
            return user_file.read_text(encoding="utf-8")
        return ""

    def delete_user_profile(self, user_id: str) -> bool:
        """Delete user profile file.
        
        Returns:
            True if deleted, False if not found.
        """
        user_file = self._get_user_file(user_id)
        if user_file.exists():
            user_file.unlink()
            return True
        return False

    def get_user_info_for_agent(self, user_id: str) -> dict:
        """Get user info formatted for agent context.
        
        Returns:
            Dict with user_id, display_name, about for agent use.
        """
        user_file = self._get_user_file(user_id)
        
        if not user_file.exists():
            return {"user_id": user_id}
        
        content = user_file.read_text(encoding="utf-8")
        lines = content.split("\n")
        
        info = {"user_id": user_id}
        in_about = False
        about_lines = []
        
        for line in lines:
            if line.startswith("- **Display Name:**"):
                info["display_name"] = line.split(":", 1)[1].strip()
            elif line.strip() == "## About":
                in_about = True
            elif in_about:
                if line.startswith("---"):
                    break
                about_lines.append(line)
        
        about_text = "\n".join(about_lines).strip()
        if about_text and about_text != "_No description provided._":
            info["about"] = about_text
        
        return info


# Global instance
_user_memory_service: Optional[UserMemoryService] = None


def get_user_memory_service() -> UserMemoryService:
    """Get or create the global user memory service."""
    global _user_memory_service
    if _user_memory_service is None:
        _user_memory_service = UserMemoryService()
    return _user_memory_service
